repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: [-l, "80"]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
    -   id: autoflake
        args: ["--remove-all-unused-imports", "--recursive", "--remove-unused-variables", --in-place, "--exclude=__init__.py"]

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        args: ["--ignore=E501,W503,E203,E402"]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-width", "80"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        args: ["--ignore-missing-imports", "--no-site-packages", "--follow-imports", "skip"]
        additional_dependencies: ['types-requests']
